var taskList = 30
var studentDetails = null
let empNo = 3891
let portNo = 2312
let categoryType = "name"
const favFruit = "Mango"
const nickName = "aadhi"
const most_used_app = "youtube"
const storage_limit = 55
const interested_students = 90
const allotedTime = "3 hours"
const InstalledGames = 3
const AcceptedName = 90
const LessonCount = 3
const minDuration = 1
const resumeCount = 89
const ManagerName = "David"
const project_file_space = "3mb"
var totalBooks = 45
var employeeStatus = null
let studentAge = 21
let roomNumber = 102
let departmentName = "Computer Science"
const favColor = "Blue"
const userName = "Arun"
const most_visited_site = "Google"
const maximumUsers = 100
const completedTasks = 75
const meetingDuration = "2 hours"
const totalProjects = 5